spring:
  kafka:
    bootstrap-servers: 172.21.100.2:9092,172.21.100.3:9092,172.21.100.6:9092

app:
  topic:
    foo: NewSaleLteProvisionDeProvisionTopic

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.memorynotfound: DEBUG